---
name: CI Pipeline

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Build using Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install the dependencies - Node.js ${{ matrix.node-version }}
              run: npm ci

            - name: Linting - Node.js ${{ matrix.node-version }}
              run: npm run lint

            - name: Unit testing - Node.js ${{ matrix.node-version }}
              run: npm test